
# =============================================================================
# Qdrant Configuration for Mac Studio M3 Ultra
# =============================================================================
# Optimized for 256GB unified memory and vector similarity search workloads

# -----------------------------------------------------------------------------
# STORAGE CONFIGURATION
# -----------------------------------------------------------------------------
storage:
  # Storage paths
  storage_path: "/qdrant/storage"
  snapshots_path: "/qdrant/snapshots"
  temp_path: "/qdrant/temp"
  
  # Storage optimization
  performance:
    max_search_threads: 8
    max_optimization_threads: 4
  
  # Quantization settings
  quantization:
    always_ram: true
    
  # On-disk payload storage
  on_disk_payload: false

# -----------------------------------------------------------------------------
# SERVICE CONFIGURATION
# -----------------------------------------------------------------------------
service:
  # Network settings
  host: "0.0.0.0"
  http_port: 6333
  grpc_port: 6334
  
  # CORS settings
  enable_cors: true
  cors_origins: ["*"]
  
  # API settings
  max_request_size_mb: 32
  max_workers: 8
  
  # TLS settings (disabled for internal Docker network)
  enable_tls: false
  # tls_config:
  #   cert: "/qdrant/tls/cert.pem"
  #   key: "/qdrant/tls/key.pem"

# -----------------------------------------------------------------------------
# CLUSTER CONFIGURATION
# -----------------------------------------------------------------------------
cluster:
  # Disable clustering for single-node setup
  enabled: false
  
  # Cluster settings (for future scaling)
  # p2p:
  #   port: 6335
  # consensus:
  #   tick_period_ms: 100

# -----------------------------------------------------------------------------
# LOGGING CONFIGURATION
# -----------------------------------------------------------------------------
log_level: "INFO"

# Telemetry (disabled for privacy)
telemetry_disabled: true

# -----------------------------------------------------------------------------
# HNSW INDEX CONFIGURATION
# -----------------------------------------------------------------------------
hnsw_config:
  # Index construction parameters
  m: 16                    # Number of bi-directional links for each node
  ef_construct: 100        # Size of the dynamic candidate list
  
  # Search parameters
  full_scan_threshold: 10000    # Use full scan for small collections
  max_indexing_threads: 8       # Maximum threads for indexing
  
  # Memory optimization
  on_disk: false               # Keep index in memory for performance
  payload_m: 16                # M parameter for payload index

# -----------------------------------------------------------------------------
# OPTIMIZER CONFIGURATION
# -----------------------------------------------------------------------------
optimizers_config:
  # Deletion threshold
  deleted_threshold: 0.2       # Rebuild segment when 20% deleted
  
  # Vacuum settings
  vacuum_min_vector_number: 1000
  
  # Segment settings
  default_segment_number: 0    # Auto-determine segment count
  max_segment_size: 5000000    # 5M vectors per segment
  
  # Memory mapping
  memmap_threshold: 50000      # Use mmap for segments larger than 50k vectors
  
  # Indexing threshold
  indexing_threshold: 20000    # Start indexing after 20k vectors
  
  # Flush settings
  flush_interval_sec: 5        # Flush every 5 seconds
  
  # Optimization threads
  max_optimization_threads: 4

# -----------------------------------------------------------------------------
# WAL CONFIGURATION
# -----------------------------------------------------------------------------
wal_config:
  # WAL capacity
  wal_capacity_mb: 32
  
  # WAL segments
  wal_segments_ahead: 0

# -----------------------------------------------------------------------------
# COLLECTION DEFAULTS
# -----------------------------------------------------------------------------
collection_config:
  # Default vector configuration
  vectors:
    size: 1536               # Default for OpenAI embeddings
    distance: "Cosine"       # Default distance metric
    
  # Default HNSW configuration
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
    max_indexing_threads: 8
    
  # Default optimizer configuration
  optimizer_config:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size: 5000000
    memmap_threshold: 50000
    indexing_threshold: 20000
    flush_interval_sec: 5
    max_optimization_threads: 4
    
  # Default quantization
  quantization_config:
    scalar:
      type: "int8"
      quantile: 0.99
      always_ram: true

# -----------------------------------------------------------------------------
# PERFORMANCE TUNING
# -----------------------------------------------------------------------------
performance:
  # Search performance
  max_search_threads: 8
  search_hnsw_ef: 128         # ef parameter for search
  
  # Indexing performance
  max_indexing_threads: 8
  indexing_batch_size: 1000
  
  # Memory management
  max_concurrent_searches: 100
  
  # I/O optimization
  async_scorer: true
  
  # Prefetch settings
  enable_prefetch: true
  prefetch_size: 1000

# -----------------------------------------------------------------------------
# MEMORY CONFIGURATION
# -----------------------------------------------------------------------------
memory:
  # Memory limits
  max_memory_usage_mb: 16384   # 16GB limit for Qdrant
  
  # Memory optimization
  mmap_threshold_mb: 100       # Use memory mapping for files > 100MB
  
  # Cache settings
  segment_cache_size: 1000
  
  # Garbage collection
  gc_interval_sec: 300         # Run GC every 5 minutes

# -----------------------------------------------------------------------------
# SECURITY CONFIGURATION
# -----------------------------------------------------------------------------
security:
  # API key authentication (if needed)
  # api_key: "${QDRANT_API_KEY}"
  
  # Read-only mode
  read_only: false
  
  # Enable HTTPS (disabled for internal Docker network)
  enable_https: false

# -----------------------------------------------------------------------------
# MONITORING AND METRICS
# -----------------------------------------------------------------------------
monitoring:
  # Enable metrics collection
  enable_metrics: false

  # Metrics endpoint
  metrics_path: "/metrics"

  # Health check
  health_check_path: "/health"

  # Telemetry
  enable_telemetry: false

# -----------------------------------------------------------------------------
# BACKUP AND RECOVERY
# -----------------------------------------------------------------------------
backup:
  # Snapshot settings
  snapshot_compression: true
  
  # Backup retention
  max_snapshots: 10
  
  # Automatic snapshots
  auto_snapshot_interval_sec: 3600  # Hourly snapshots

# -----------------------------------------------------------------------------
# EXPERIMENTAL FEATURES
# -----------------------------------------------------------------------------
experimental:
  # Enable experimental features
  enable_experimental_features: false
  
  # GPU acceleration (if available)
  # gpu_acceleration: true
  
  # Advanced indexing
  # enable_advanced_indexing: false

# -----------------------------------------------------------------------------
# COLLECTION-SPECIFIC CONFIGURATIONS
# -----------------------------------------------------------------------------
# These can be overridden when creating collections

# Configuration for document embeddings
document_collection_config:
  vectors:
    size: 1536
    distance: "Cosine"
  hnsw_config:
    m: 32                    # Higher connectivity for better recall
    ef_construct: 200        # Higher ef_construct for better quality
    full_scan_threshold: 5000
  optimizer_config:
    indexing_threshold: 10000
    max_segment_size: 2000000

# Configuration for code embeddings
code_collection_config:
  vectors:
    size: 768
    distance: "Cosine"
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
  optimizer_config:
    indexing_threshold: 20000
    max_segment_size: 5000000

# Configuration for user embeddings
user_collection_config:
  vectors:
    size: 384
    distance: "Cosine"
  hnsw_config:
    m: 8                     # Lower connectivity for smaller vectors
    ef_construct: 64
    full_scan_threshold: 20000
  optimizer_config:
    indexing_threshold: 50000
    max_segment_size: 10000000

# -----------------------------------------------------------------------------
# AGENTIC AI SPECIFIC OPTIMIZATIONS
# -----------------------------------------------------------------------------
agentic_ai_config:
  # Optimize for mixed workloads
  mixed_workload_optimization: true
  
  # Batch processing settings
  batch_processing:
    max_batch_size: 1000
    batch_timeout_ms: 100
    
  # Real-time search optimization
  real_time_search:
    enable_streaming: true
    stream_batch_size: 100
    
  # Multi-tenant isolation
  multi_tenant:
    enable_collection_isolation: true
    max_collections_per_tenant: 100
    
  # Workflow integration
  workflow_integration:
    enable_webhooks: true
    webhook_timeout_ms: 5000
    
  # Caching strategy
  caching:
    enable_query_cache: true
    cache_ttl_sec: 300
    max_cache_size_mb: 1024

# -----------------------------------------------------------------------------
# DEVELOPMENT AND DEBUGGING
# -----------------------------------------------------------------------------
debug:
  # Enable debug mode
  debug_mode: false
  
  # Profiling
  enable_profiling: false
  profiling_interval_sec: 60
  
  # Detailed logging
  log_queries: false
  log_performance: false
  
  # Memory debugging
  log_memory_usage: false
  memory_check_interval_sec: 300
